class Engineering{
	
public static void main(String[] args)
{
	String Apple="There is a girl by the track";
	String ball="i'm coffee lover";
    String cat="cat lover";
	String dog="dog lover";
	String eagle="eagle lover";
	String rock="rock is hard";
	String good="health is wealth";
	String home="who is she?";
	String iron="Sahana Khemannavar";
	String jack="i sketch a lot";
	String king="the kin";
	String loan="loan given by bank";
	String man="man power";
    String nest="take a glance";
	String oak="oh my god!";
	String poet="poet has a great vision";
	String quite="i'm leaving";
	String read="i'm reading";
	String steel="he stole the book";
	String table="book is on the table";
	String umbrella="umbrella used in rainy season";
	String van="i'll go by bus";
	String wax="i'm sick";
	String xray="this is my xray";
    String yoyo="i'm talking";
	String zeebra="my goal";	
	String Apple1="who is this?";
	String ball1="get the ball";
    String cat1="my goat";
	String dog1="they are going";
	String eagle1="i hope you get the mail";
	String rock1="i'm rocking";
	String good1="they are good";
	String home1="my hope";
	String iron1="about my day";
	String jack1="this is aleana";
	String king1="where is the value";
	String loan1="man of the match";
	String man1="my money";
    String nest1="the holy ";
	String oak1="my rules";
	String poet1="book author";
	String quite1="are you coming";
	String read1="go for lunch";
	String steel1="book has the words";
	String table1="my table";
	String umbrella1="There is a girl by the track";
	String van1="what is the meaning";
	String wax1="you are the best";
	String xray1="my suggetion";
    String yoyo1="self respect";
	String zeebra1="which area?";
	String Apple2="sunny mornig";
	String ball2="city of stars";
    String cat2="something is bad";
	String dog2="my words1";
	String eagle2="They are tracking ";
	String rock2="what's up";
	String good2="here is the example";
	String home2="old lady coming";
	String iron2="his dog barks";
	String jack2="My school starts at 8:00 AM";
	String king2="i eat vegitables";
	String loan2="he is my enemy";
	String man2="nice to meet you";
    String nest2="good morning";
	String oak2="the moon is shining";
	String poet2="he play tennis";
	String quite2="i'm singer";
	String read2="cates hate water";
	String steel2="dont smoke";
	String table2="he struck a macth";
	String umbrella2="tell the truth";
	String van2="sugar is sweet";
	String wax2="There is a girl by the track";
	String Apple3="There is a girl by the track"+"help her";
	String ball3="school"+"life";
    String cat3="Aman"+"dahi";
	String dog3="another"+"name";
	String eagle3="by"+"pass";
	String rock3="cup"+"cake";
	String good3="salary"+"hike";
	String home3=quite2+"i can sing";
	String iron3=read2+"they dont drink";
	String jack3=cat2+"dont go out";
	String king3=king2+"not nonveg";
	String loan3=loan2+"dont of with him";
	String man3=nest2+"breakfast";
    String nest3=oak2+"see there";
	String oak3="my"+"fault";
	String poet3="they are"+"my relatives";
	String quite3="whats"+"going";
	String read3="the time for"+"good things";
	String steel3="whats the"+"matter";
	String table3="the way"+"she breath";
	String umbrella3="what is"+"The matter";
	String van3=oak2+"see there";
	String wax3=read2+"they dont drink";
	String xray3="they are"+"my relatives";
    String yoyo3="whats"+"going";
	String zeebra3="whats the"+"matter";
	String Apple4=cat2+"dont go out";
	String ball4=quite2+"i can sing";
    String cat4="school"+"life";
	String dog4="the way"+"she breath";
	String eagle4="what is"+"The matter";
	String rock4="the time for"+"good things";
	String good4="they are"+"my relatives";
	String home4="whats"+"going";
	String iron4=quite2+"i can sing";
	String jack4="the time for"+"good things";
	String king4="they are"+"my relatives";
	String loan4="what is"+"The matter";
	String man4="whats the"+"matter";
    String nest4="whats the"+"matter";
	String oak4="whats the"+"matter";
	String poet4="There is a girl by the track"+"help her";
	String quite4=read2+"they dont drink";
	String read4="whats"+"going";
	String steel4="they are"+"my relatives";
	String table4="the time for"+"good things";
	String umbrella4="Aman"+"dahi";
	String van4="what is"+"The matter";
	String wax4="the way"+"she breath";
	String xray4="the time for"+"good things";
    String yoyo4="whats the"+"matter";
	String zeebra4="the time for"+"good things";	
	String Apple5="what is"+"The matter";
	String ball5="There is a girl by the track"+"help her";
    String cat5="the time for"+"good things";
	String dog5="the time for"+"good things";
	String eagle5="what is"+"The matter";
	String rock5="what is"+"The matter";
	String good5="the time for"+"good things";
	String home5="There is a girl by the track"+"help her";
	String iron5="what is"+"The matter";
	String jack5="whats"+"going";
	String king5="what is"+"The matter";
	String loan5="There is a girl by the track";
	String man5="the time for"+"good things";
    String nest5="There is a girl by the track"+"help her";
	String oak5="whats the"+"matter";
	String poet5="the time for"+"good things";
	String quite5="the time for"+"good things";
	String read5="the time for"+"good things";
	String steel5="the way"+"she breath";
	String table5="what is"+"The matter";
	String umbrella5="what is"+"The matter";
	String van5="the time for"+"good things";
	String wax5="what is"+"The matter";
	System.out.println("Apple:"+Apple);
	System.out.println("ball:"+ball);
	System.out.println("cat"+cat);
	System.out.println("dog"+dog);
	System.out.println("eagle"+eagle);
	System.out.println("rock"+rock);
	System.out.println(good);
	System.out.println(home);
	System.out.println(iron);
	System.out.println(jack);
	System.out.println(king);
	System.out.println(loan);
	System.out.println(man);
	System.out.println(nest);
	System.out.println(oak);
	System.out.println(poet);
	System.out.println(quite);
	System.out.println(read);
	System.out.println(steel);
	System.out.println(table);
	System.out.println(umbrella);
	System.out.println(van);
	System.out.println(wax);
	System.out.println(xray);
	System.out.println(yoyo);
	System.out.println(zeebra);
	System.out.println(Apple1);
	System.out.println(ball1);
	System.out.println(cat1);
	System.out.println(dog1);
	System.out.println(eagle1);
	System.out.println(rock1);
	System.out.println(good1);
	System.out.println(home1);
	System.out.println(iron1);
	System.out.println(jack1);
	System.out.println(king1);
	System.out.println(man1);
	System.out.println(nest1);
	System.out.println(oak1);
	System.out.println(poet1);
	System.out.println(quite1);
	System.out.println(read1);
	System.out.println(steel1);
	System.out.println(table1);
	System.out.println(umbrella1);
	System.out.println(van1);
	System.out.println(wax1);
	System.out.println(xray1);
	System.out.println(yoyo1);
	System.out.println(zeebra1);
	System.out.println(Apple2);
	System.out.println(ball2);
	System.out.println(cat2);
	System.out.println(dog2);
	System.out.println(eagle2);
	System.out.println(rock2);
	System.out.println(good2);
	System.out.println(home2);
	System.out.println(iron2);
	System.out.println(jack2);
	System.out.println(king2);
	System.out.println(loan2);
	System.out.println(man2);
	System.out.println(nest2);
	System.out.println(oak2);
	System.out.println(poet2);
	System.out.println(quite2);
	System.out.println(read2);
	System.out.println(steel2);
	System.out.println(table2);
	System.out.println(umbrella2);
	System.out.println(van2);
	System.out.println(wax2);
	System.out.println(Apple3);
	System.out.println(ball3);
	System.out.println(cat3);
	System.out.println(dog3);
	System.out.println(eagle3);
	System.out.println(rock3);
	System.out.println(good3);
	System.out.println(home3);
	System.out.println(iron3);
	System.out.println(jack3);
	System.out.println(king3);
	System.out.println(loan3);
	System.out.println(man3);
	System.out.println(nest3);
	System.out.println(oak3);
	System.out.println(poet3);
	System.out.println(quite3);
	System.out.println(read3);
	System.out.println(steel3);
	System.out.println(table3);
	System.out.println(umbrella3);
	System.out.println(van3);
	System.out.println(wax3);
	System.out.println(xray3);
	System.out.println(yoyo3);
	System.out.println(zeebra3);
	System.out.println(Apple4);
	System.out.println(ball4);
	System.out.println(cat4);
	System.out.println(dog4);
	System.out.println(eagle4);
	System.out.println(rock4);
	System.out.println(good4);
	System.out.println(home4);
	System.out.println(iron4);
	System.out.println(jack4);
	System.out.println(king4);
	System.out.println(loan4);
	System.out.println(man4);
	System.out.println(nest4);
	System.out.println(oak4);
	System.out.println(poet4);
	System.out.println(poet4);
	System.out.println(quite4);
	System.out.println(read4);
	System.out.println(steel4);
	System.out.println(table4);
	System.out.println(umbrella4);
	System.out.println(van4);
	System.out.println(wax4);
	System.out.println(xray4);
	System.out.println(yoyo4);
	System.out.println(zeebra4);
	System.out.println(Apple5);
	System.out.println(ball5);
	System.out.println(cat5);
	System.out.println(dog5);
	System.out.println(eagle5);
	System.out.println(rock5);
	System.out.println(good5);
	System.out.println(home5);
	System.out.println(iron5);
	System.out.println(jack5);
	System.out.println(king5);
	System.out.println(loan5);
	System.out.println(man5);
	System.out.println(nest5);
	System.out.println(oak5);
	System.out.println(poet5);
	System.out.println(quite5);
	System.out.println(read5);
	System.out.println(steel5);
	System.out.println(table5);
	System.out.println(umbrella5);
	System.out.println(van5);
	System.out.println(wax5);
}
}
	